# Java is currently unsupported on Windows, so we use a bash build and
# install it using Gravis' (https://github.com/DanySK/Gravis-CI) script.

language: bash

os:
  - linux
  - osx
  - windows

env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="1.8"

notifications:
  email:
    recipients:
      - joao.coutinho9@gmail.com
    on_success: always

before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
  - source ~/.install-jdk-travis.sh

  - ./gradlew clean build -x test --console=plain
  
  - cp build/libs/jFSTMerge-all.jar testfiles/shelltests/config/jFSTMerge.jar
  - bash testfiles/shelltests/config/gitconfiguration.sh

  - git config --global user.email "gjcc@cin.ufpe.br"
  - git config --global user.name "Guilherme Cavalcanti" 

script:
  - ./gradlew test --console=plain
  - cd testfiles/shelltests/
  - bash s3mGitIntegrationTests.sh

before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
  - bash ~/.clean_gradle_cache.sh