name: Java CI

on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            dependencies: .\;dependencies/*
          - os: ubuntu-latest
            dependencies: .:dependencies/*
          - os: macos-latest
            dependencies: .:dependencies/*

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew clean build -x test --console=plain

    - run: cp build/libs/jFSTMerge-all.jar ${HOME}/s3m.jar

    - name: Configure git integration with S3M
      run: bash testfiles/shelltests/config/gitconfiguration.sh

    - run: git config --global user.name "Guilherme Cavalcanti"
    - run: git config --global user.email "gjcc@cin.ufpe.br"

    - name: Tests
      run: ./gradlew test --console=plain

    - name: Shell Tests
      run: cd testfiles/shelltests

    - run: javac -cp ${{ matrix.dependencies }} s3mGitIntegrationTests.java
    - run: java -cp ${{ matrix.dependencies }} org.junit.runner.JUnitCore s3mGitIntegrationTests